### PR TITLE
Memory refactor

### PR DESCRIPTION
**Pull request by jwdebelius**
This addresses #25, where the code was failing at scale through a major refactor. This PR:

1. Breaks the database reconstruction from the table reconstruction
2. Sets up the database reconstruction primarily through a dask distributed pipeline. With the new pipeline, I was able to run the Silva 138 database on a scale data example in ~15 minute on four core of my macbook.
3. Adds a pipeline to wrap reconstruction (database, table, and taxonomy) to make the processing easier

@vitorheidrich - this is your issue, have you seen any more performance problems that need to be addressed?

@mikerobeson, @boulund or @luhugerth - comments/review would be really nice

Yes, it's a monster PR

### CODE REVIEW

**Comment by vitorheidrich** [comment]
Hi,

None at all! Since the proposed fix I ran the full pipeline several times with different databases and it always worked great.

Hey @luhugerth, I am also a former *moleculento* :wave: (T24). Keep up the good work y'all!

**Comment by jwdebelius** [comment]
Hey @mikerobeson I know you were looking at this, can I ping you on it?

**Comment by jwdebelius** [comment]
Hi @mikerobeson, I'm going to nudge you again. If you don't have any comments, can I merge so I can move forward on the next weird round?

**Comment by mikerobeson** [comment]
HI @jwdebelius, sorry about this. I am looking through this now.

**Pull request merged**
