### PR TITLE
Fixes documentation issues

### PR DESCRIPTION
**Pull request by jwdebelius**
In #23 and #24 small syntax issues were found in the docs. This addresses both of these. @luhugerth or @mikerobeson, could you review?

### CODE REVIEW

**Comment by mikerobeson** [comment]
I'll look through this today.

**Review by mikerobeson — APPROVED** [review]
This LGTM!

**Comment by jwdebelius** [comment]
Thanks @mikerobeson! Can you merge, or should I merge?

**Comment by mikerobeson** [comment]
I'll merge now. :-)

**Comment by mikerobeson** [comment]
Actually.. I do not think I can merge... no write access.

**Comment by jwdebelius** [comment]
I added you with write access, but then I'm going to the very bad thing of merging my own PR

**Comment by mikerobeson** [comment]
Haha, no worries. I can confirm that I now have write access. Thanks! :-)

**Pull request merged**
